#!/bin/sh

# The setting for a generic X11 session are in xprofile
if [-f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
    "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
    . "$HOME/.xprofile"
fi

# Start an xsession

# Here DWM is kept as default
session=${1:-dwm}

case $session in
    dwm             ) exec dwm;;
    i3|i3wm         ) exec i3;;
    bspwm           ) exec bspwm;;
    xfce|xfce4      ) exec startxfce4;;
    # No known session, try to run it as command
    *               ) exec $1;;
esac

