#!/bin/sh

# Set dpi
xrandr --dpi 92

#
# Set Wallpaper
#
# restore previous wallpaper
$HOME/.scripts/wallpaper.sh &
# pick random wallpaper
#$HOME/.scripts/wallpaper.sh $HOME/Pictures/wallpapers & # pick random wallpaper

# Load Xresources
xrdb ${XDG_CONFIG_HOME:-$HOME.config}/X11/Xresources & xrdbpid=$!

# Autostart some Programs
pidof -s dunst || dunst &
pidof -s dwmblocks || dwmblocks &
pidof -s picom || picom &
pidof -s unclutter || unclutter &
pidof -s udiskie || udiskie  &
pidof -s sxhkd || sxhkd &

#Wait fo xrdb if neccesary
[ -n "$xrdbpid" ] && wait "$xrdbpid"

