#+TITLE: DOOM Emacs Config
#+AUTHOR: Jonas Schwind
#+DESCRIPTION: My Doom Emacs config
#+PROPERTY: header-args :tangle config.el
#+auto_tangle: t
#+STARTUP: showeverything

* Table of Contents :toc:
- [[#about-this-config][About this config]]
  - [[#requirements][Requirements]]
- [[#splash-screen][Splash screen]]
- [[#beacon][Beacon]]
- [[#identification][Identification]]
- [[#stop-loosing-files][Stop loosing files]]
- [[#fonts][Fonts]]
- [[#doom-theme][Doom Theme]]
- [[#line-settings][Line Settings]]
- [[#org-mode][Org-Mode]]
- [[#org-fonts][Org-Fonts]]
- [[#org-auto-tangle][Org auto-tangle]]
- [[#package-configuration][Package configuration]]

* About this config
This is your private configuration.
It is supposed to be uses in DOOM Emacs
Remember, you do not need to run 'doom sync' after modifying this file!
#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

** Requirements
Just put these in your /'packages.el'/
#+begin_example emacs-lisp
(package! writeroom-mode) ;; Distraction free writing
(package! org-auto-tangle) ;; Autotangle on save
(package! beacon) ;; Neve loose cursor
#+end_example

* Splash screen
#+begin_src emacs-lisp
(setq fancy-splash-image (concat doom-user-dir "splash/doom-emacs-dracula-green.png"))
#+end_src

* Beacon
#+begin_src emacs-lisp
(beacon-mode t)
#+end_src

* Identification
Some functionality uses this to identify you, e.g. GPG configuration, email clients, file templates and snippets.
#+begin_src emacs-lisp
(setq user-full-name "Jonas Schwind"
      user-mail-address "jonasschwind20021@gmx.de")
#+end_src

* Autosave
#+begin_src emacs-lisp
(setq auto-save-default t make-backup-files t)
#+end_src

* Fonts
Doom exposes five (optional) variables for controlling fonts in Doom:
+ /doom-font/ -- the primary font to use
+ /doom-variable-pitch-font/ -- a non-monospace font (where applicable)
+ /doom-big-font/ -- used for `doom-big-font-mode'; use this for presentations or streaming.
+ /doom-unicode-font/ -- for unicode glyphs
+ /doom-serif-font/ -- for the `fixed-pitch-serif' face

See 'C-h v doom-font' for documentation and more examples of what they accept.

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "SFMono Nerd Font" :size 15)
      doom-variable-pitch-font (font-spec :family "Ubuntu Nerd Font" :size 15)
      doom-big-font (font-spec :family "SFMono Nerd Font" :size 24))
(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))
(custom-set-faces!
  '(font-lock-comment-face :slant italic)
  '(font-lock-keyword-face :slant italic))
#+end_src

If you or Emacs can't find your font, use 'M-x describe-font' to look them up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to refresh your font settings.
If Emacs still can't find your font, it likely wasn't installed correctly. Font issues are rarely Doom issues!

* Doom Theme
There are two ways to load a theme. Both assume the theme is installed and available. You can either set `doom-theme' or manually load a theme with the `load-theme' function.
#+begin_src emacs-lisp
(setq doom-theme 'doom-dracula)
#+end_src

* Line Settings
This determines the style of line numbers in effect. If set to `nil', line numbers are disabled. For relative line numbers, set this to `relative'.
#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src

Automaticaly wrap lengthy lines.
#+begin_src emacs-lisp
(+global-word-wrap-mode +1)
#+end_src

* Org-Mode
If  you use `org' and don't want your org files in the default location below, change `org-directory'. It must be set before org loads!
#+begin_src emacs-lisp
(after! org
  (setq org-directory "~/org/"
        org-hide-emphasis-markers t
        org-log-done 'time
        org-src-fontify-natively t
        org-src-tab-acts-natively t))
#+end_src

* Org-Fonts
#+begin_src emacs-lisp
(with-eval-after-load 'org-faces
  (dolist
      (face
       '((org-level-1 1.7 "#51afef" ultra-bold)
         (org-level-2 1.6 "#c678dd" extra-bold)
         (org-level-3 1.5 "#98be65" bold)
         (org-level-4 1.4 "#da8548" semi-bold)
         (org-level-5 1.3 "#5699af" normal)
         (org-level-6 1.2 "#a9a1e1" normal)
         (org-level-7 1.1 "#46d9ff" normal)
         (org-level-8 1.0 "#ff6c6b" normal)))
    (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
    (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))
#+end_src

* Org auto-tangle
Automaticaly run org-babel-tangle on save
#+begin_src emacs-lisp
(use-package org-auto-tangle
  :defer t
  :hook (org-mode . org-auto-tangle-mode)
  :config (setq org-auto-tangle-default t))
#+end_src

* Package configuration
Whenever you reconfigure a package, make sure to wrap your config in an `after!' block,
otherwise Doom's defaults may override your settings. E.g.

#+begin_example emacs-lisp
   (after! PACKAGE
     (setq x y))
#+end_example

The exceptions to this rule:
+ Setting file/directory variables (like `org-directory')
+ Setting variables which explicitly tell you to set them before their package is loaded (see 'C-h v VARIABLE' to look up their documentation).
+ Setting doom variables (which start with 'doom-' or '+').

Here are some additional functions/macros that will help you configure Doom.
+ `load!' for loading external *.el files relative to this one
+ `use-package!' for configuring packages
+ `after!' for running code after a package has loaded
+ `add-load-path!' for adding directories to the `load-path', relative to this file. Emacs searches the `load-path' when you load packages with `require' or `use-package'.
+ `map!' for binding new keys

To get information about any of these functions/macros, move the cursor over the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
This will open documentation for it, including demos of how they are used.
Alternatively, use `C-h o' to look up a symbol (functions, variables, faces, etc).

You can also try 'gd' (or 'C-c c d') to jump to their definition and see how they are implemented.
