#! /bin/sh

#   ┌─────────────────────────────────────┐
#   │    ____ _____ ____ _       ____  ___│
#   │   / __ ) ___// __ \ |     / /  |/  /│
#   │  / __  \__ \/ /_/ / | /| / / /|_/ / │
#   │ / /_/ /__/ / ____/| |/ |/ / /  / /  │
#   │/_____/____/_/     |__/|__/_/  /_/   │
#   │                                     │
#   └─────────────────────────────────────┘


#### Autostart ####
pgrep -x nitrogen > /dev/null || nitrogen --restore &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &


#### Multimonitor ####
xrandr -q | grep 'HDMI1 connected' && xrandr --output eDP1 --primary --mode 1336-768 --rotate normal --mode 1920x1080 --rotate normal --right-of eDP1

bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8 9 0


#### BSPWM basic config ####
bspc config border_width                    3
bspc config window_gap                      5
bspc config top_padding                     0
bspc config bottom_padding                  0
bspc config left_padding                    0
bspc config right_padding                   0
bspc config split_ratio                     .5

bspc config single_monocle                  false
bspc config borderless_monocle              true
bspc config gapless_monocle                 true

bspc config focus_follows_pointer           false
bspc config click_to_focus                  true
bspc config focus_by_distance               true
bspc config history_aware_focus             true
bspc config remove_disabled_monitors        true
bspc config merge_overlapping_monitors      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


#### BSPWM coloring ####
#bspc config normal_border_color     "#44475a"
#bspc config active_border_color     "#44475a"       # Previously  "#bd93f9"
#bspc config focused_border_color    "#ff79c6"
#bspc config presel_feedback_color   "#6272a4"


#### BSPWM RULES ####
bspc rule -a mpv state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Galculator state=floating

